In [1]:
import numpy as np
import cvxpy as cp

In [2]:
# Definir variáveis k1, k2, m1, m2, c0
k1, k2, m1, m2, c0 = 1, 1, 1, 0.5, 2
# Definir as matrizes A, B e C
A = np.array([[0, 0, 1, 0],
              [0, 0, 0, 1],
              [-(k1+k2)/m1, k2/m1, -c0/m1, 0],
              [k2/m2,-k2/m2,0,-c0/m2]])

B = np.array([[0],[0],[1/m1],[0]])

C = np.array([[0,1,0,0]])

rows, cols = A.shape[0], A.shape[1]

# Definir as variáveis de otimização
W = cp.Variable((rows, cols), symmetric=True)

rho = cp.Variable()

# Definir a função objetivo: min (rho)
objective = cp.Minimize(rho)

# Definir as restrições
constraints = [W>>0,
               W.T>>0,
               rho >= cp.trace(C@W@C.T),
               A@W + W@A.T + B@B.T << 0]

# Criar e resolver o problema de otimização
problem = cp.Problem(objective, constraints)
problem.solve()

# Verificar o status da solução
if problem.status == cp.OPTIMAL:
    print("Status: Ótimo\n")
    print("Valor mínimo de rho:",problem.value)
    print("\nMatriz P:\n", W.value)
else:
    print("O problema não tem uma solução ótima. Status:", problem.status)

Status: Ótimo

Valor mínimo de rho: 0.09259255050141106

Matriz P:
 [[ 1.57407371e-01  8.33332702e-02 -5.63391371e-09  3.70370438e-02]
 [ 8.33332702e-02  9.25925457e-02 -3.70370196e-02 -8.07919129e-09]
 [-5.63391371e-09 -3.70370196e-02  2.31481494e-01 -1.28132760e-08]
 [ 3.70370438e-02 -8.07919129e-09 -1.28132760e-08  1.85185256e-02]]
