In [10]:
import numpy as np
import cvxpy as cp

In [9]:
# Definir variáveis k1, k2, m1, m2, c0
k1, k2, m1, m2, c0 = 1, 1, 1, 0.5, 2
# Definir as matrizes A, B e C
A = np.array([[0, 0, 1, 0],
              [0, 0, 0, 1],
              [-(k1+k2)/m1, k2/m1, -c0/m1, 0],
              [k2/m2, -k2/m2, 0, -c0/m2]])

B = np.array([[0], [0], [1/m1], [0]])

C = np.array([[0, 1, 0, 0]])

D = np.array([[0]])

n, p = A.shape[0], B.shape[1]

# Definir as variáveis de otimização
P = cp.Variable((n, n), symmetric=True)

mu = cp.Variable()

# Definir a função objetivo: min (mu)
objective = cp.Minimize(mu)

# Definir os blocos da LMI
M11 = A.T @ P + P @ A + C.T @ C
M12 = P @ B + C.T @ D
M21 = B.T @ P + D.T @ C
M22 = D.T @ D - mu

# Construir a matriz de blocos LMI
LMI = cp.bmat([
    [M11, M12],
    [M21, M22]
])

# Definir as restrições corrigidas
constraints = [P >> 0,
               LMI << 0]

# Criar e resolver o problema de otimização
problem = cp.Problem(objective, constraints)
problem.solve()

# Verificar o status da solução
if problem.status == cp.OPTIMAL or problem.status == cp.OPTIMAL_INACCURATE:
    print("Status:", problem.status, "\n")
    print("Valor ótimo de mu:",problem.value)
    print("Matriz P:\n",P.value)
else:
    print("O problema não tem uma solução ótima. Status:", problem.status)

Status: optimal 

Valor ótimo de mu: 1.0000002383582647
Matriz P:
 [[1.25333379 0.74666663 0.29393798 0.01084982]
 [0.74666663 3.25333407 0.70606232 0.98915039]
 [0.29393798 0.70606232 0.3575597  0.21513624]
 [0.01084982 0.98915039 0.21513624 0.76581751]]
